version: '3.8'

services:
  cheesesheet:
    build: .
    container_name: cheesesheet
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    env_file:
      - .env.docker
    volumes:
      - cheesesheet_latex:/tmp/cheesesheet_latex
      - cheesesheet_logs:/app/logs
      - cheesesheet_uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
        reservations:
          memory: 1G
          cpus: '0.5'

  redis:
    image: redis:7-alpine
    container_name: cheesesheet_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  cheesesheet_latex:
  cheesesheet_logs:
  cheesesheet_uploads:
  redis_data:

networks:
  default:
    name: cheesesheet_network
    driver: bridge