services:
  cheesesheet-backend:
    build: 
      context: ..
      dockerfile: backend-docker/Dockerfile
    container_name: cheesesheet_backend_split
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - FRONTEND_URL=https://your-app.vercel.app
    env_file:
      - ../.env.docker
    volumes:
      - cheesesheet_latex:/tmp/cheesesheet_latex
      - cheesesheet_logs:/app/logs
      - cheesesheet_uploads:/app/uploads
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'

  redis:
    image: redis:7-alpine
    container_name: cheesesheet_redis_backend
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

volumes:
  cheesesheet_latex:
  cheesesheet_logs:
  cheesesheet_uploads:
  redis_data: